### ISSUE TITLE
Unable to forge

### ISSUE THREAD

**Issue by SuperTyrael** [z-t-y/Flog#1]
Hi， when I execute ```flask forge```, there occurred some errors.
```
Traceback (most recent call last):
  File "/Users/liam/Desktop/Git/Flog/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/liam/Desktop/Git/Flog/flog/commands.py", line 44, in forge
    Role.insert_roles()
  File "/Users/liam/Desktop/Git/Flog/flog/models.py", line 187, in insert_roles
    role = Role.query.filter_by(name=r).first()
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3397, in first
    ret = list(self[0:1])
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3171, in __getitem__
    return list(res)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/Users/liam/Desktop/Git/Flog/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: roles
[SQL: SELECT roles.id AS roles_id, roles.name AS roles_name, roles."default" AS roles_default, roles.permissions AS roles_permissions 
FROM roles 
WHERE roles.name = ?
 LIMIT ? OFFSET ?]
[parameters: ('User', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by z-t-y** [comment]
It seems that you haven't run a `flask deploy` to insert the roles to the database. Run `flask deploy` with your current database and try again.

Also, it seems that Flog doesn't go with sqlite3 on my local machine. If there are still errors, try mysql or postgresql instead.

**Comment by z-t-y** [comment]
Sorry for that. I forget to add `flask deploy` to README.md. I'll add this line to README.md before 2021.1.15 (I'm pretty busy these days).
